version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: server/flask.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/Learning_platform/server
    environment:
      CODE_DB_HOST: mysql_db
      CODE_DB_USER: CODE_USER
      CODE_DB_PASSWORD: CODE_PASSWORD
      CODE_DB_NAME: CODE_DB
      PYTHONPATH: /Learning_platform
    depends_on:
      - mysql
      - code-executor

  client:
      build:
        context: .
        dockerfile: client/vite.dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./client:/Learning_platform/client
        - /Learning_platform/client/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
      stdin_open: true
      tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: CODE_DB
      MYSQL_USER: CODE_USER
      MYSQL_PASSWORD: CODE_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  code-executor:
    image: python:3.8-slim
    container_name: code_executor
    volumes:
      - ./executor:/executor
    working_dir: /executor
    entrypoint: ["tail", "-f", "/dev/null"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

volumes:
  mysql_data:
